baseURL = 'https://dingyiyi0226.github.io/geoguessr-note/'
languageCode = 'en-us'
title = 'Geoguessr Note'
theme = 'hugo-book'
enableGitInfo = true

[menus]
[[menus.after]]
  name = "Github"
  url = "https://github.com/dingyiyi0226/geoguessr-note"
[params]
  BookTheme = 'light'
  BookRepo = 'https://github.com/dingyiyi0226/geoguessr-note'
  BookLastChangeLink = 'https://github.com/dingyiyi0226/geoguessr-note/commit/{{ .GitInfo.Hash }}'
  BookEditLink = 'https://github.com/dingyiyi0226/geoguessr-note/edit/master/{{ .Path }}'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true