baseURL = 'https://dingyiyi0226.github.io/geoguessr-note/'
languageCode = 'en-us'
title = 'Geoguessr Note'
theme = 'hugo-book'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup.goldmark.renderer]
  unsafe = true